name: Build and test rmlint (master)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      RM_TS_DIR: "/tmp/rmlint-unit-testdir"
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: "Check changes"
        # TODO also include skipping build but allow docs to be processed
        shell: bash
        run: |
          if git diff --exit-code --name-only HEAD^ HEAD ':!.gitignore' ':!docs' ':!*.md' ':!*.txt' ':!*.yml'; then
            echo "SKIP_CHANGES=true" >> $GITHUB_ENV
            echo "SKIP_CHANGES = true"
          else
            echo "SKIP_CHANGES=false" >> $GITHUB_ENV
            echo "SKIP_CHANGES = false"
          fi
      - name: "Should we test"
        run:
          echo "the answer is ${{ env.SKIP_CHANGES }}"

      - name: "Test it"
        if: ! ${{ env.SKIP_CHANGES == 'false' }}
        run: |
          echo "RUNNING IT... "
